title: Ergonautas
description: Programación funcional en español

collections:
  terms:
    output: false

permalink: pretty

exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

include:
- _pages
